# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
steps:
- script: 'C:\agents\vsts-agent-win-x64-2.204.0\_work\ToscaCI\Client\ToscaCIClient.exe -m local -t junit -r C:\Temp\ToscaCI.xml'
  displayName: ToscaCI

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/ToscaCI-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Publish Tosca Results'